# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
    game.loader.text:
        class: AppBundle\Game\Loader\TextFileLoader
    game.loader.xml:
        class: AppBundle\Game\Loader\XmlFileLoader
    game.wordlist:
        class: AppBundle\Game\WordList
        calls:
            - ['addLoader', ['txt', '@game.loader.text']]
            - ['addLoader', ['xml', '@game.loader.xml']]
            - ['addWord', ['customer']]
            - ['addWord', ['lemonade']]
            - ['addWord', ['employee']]
            - ['loadDictionaries', ['%dictionaries%']]
    game.context:
        class: AppBundle\Game\GameContext
        arguments: ['@session']
    game.runner:
        class: AppBundle\Game\GameRunner
        arguments: ['@game.context', '@game.wordlist']